### ISSUE TITLE
Error with removeEventListener

### ISSUE THREAD

**Issue by Shohzodt** [takuma-ru/vue_SwipeModal#7]
document.querySelector(`#modal`).removeEventListener("scroll", this.handleScroll);

Hey, in my project i have used this package, but when i wanted to close it after some action, error above is happening so i went to node modules folder and changed beforeDestroy hook a little bit, firstly I have checked where var el = document.querySelector(`#modal`); is there or not so,
if(el){
      document.querySelector(`#modal`).removeEventListener("scroll", this.handleScroll);
}
error is fixed now, can you please check it, thanks it is a great package

**Comment by takuma-ru** [comment]
Thanks for the feedback.
I will check the error and release a fix soon.
By the way, could you please tell me which browser and OS the error occurred on?

**Comment by Shohzodt** [comment]
Thanks, it is Chrome

**Comment by takuma-ru** [comment]
Bug fix version released (v1.0.0)
